package com.shitian.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	/**
	 * 绑定数据库表和model映射
	 * @param arp
	 */
	public static void mapping(ActiveRecordPlugin arp) {
		//arp.addMapping("blog", "id", User.class);
	}
}

