package com.shitian.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.shitian.modules.front.model.User;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	/**
	 * 绑定数据库表和model映射
	 * @param arp
	 */
	public static void mapping(ActiveRecordPlugin arp) {
		//param1:表名  [param2:表主键]  param3:Model类
		//arp.addMapping("t_user", User.class);
		arp.addMapping("t_users", "id", User.class);
	}
}

